'use client'
import Header from '@components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import Footer from '@components/Footer'
import UseProvider from '@redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const path = usePathname()
  return (
    <html lang="en">
      <body
        className={` bg-red-200 inter.className 
          ${path === '/' && 'bg-lime-100'}
          ${path === '/projects' && 'bg-blue-100'}
          `}
      >
        <UseProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="mb-auto bg-slate-100">{children}</main>
            <Footer />
          </div>
        </UseProvider>
      </body>
    </html>
  )
}
